package GeneralClasses.model;

public enum CommandType {
    FILE,
    FILE_REQUEST,
    LIST,
    CHANGE_OUT_SERVER_DIR,
    CHANGE_IN_SERVER_DIR,
    VIEW_SERVER_DIR,
    CREATE_NEW_PATH,
    DELETE,
    LOGIN_AND_PASSWORD_MESSAGE,
    REGISTRY_LOGIN_AND_PASSWORD_MESSAGE,

    ACCESSED_MESSAGE,
    ACCESS_DENIED_MESSAGE,

    REGISTRY_SUCCESSFUL,
    REGISTRY_DENIED
}
